//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36282
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Index.
        /// </summary>
        internal static string AddDocumentsToIndexText {
            get {
                return ResourceManager.GetString("AddDocumentsToIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearLogButtonText {
            get {
                return ResourceManager.GetString("ClearLogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Question.
        /// </summary>
        internal static string ConfirnQuestion {
            get {
                return ResourceManager.GetString("ConfirnQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create in memory.
        /// </summary>
        internal static string CreateInMemoryText {
            get {
                return ResourceManager.GetString("CreateInMemoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateText {
            get {
                return ResourceManager.GetString("CreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Indexes:.
        /// </summary>
        internal static string CurrentIndexesText {
            get {
                return ResourceManager.GetString("CurrentIndexesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteIndexButtonText {
            get {
                return ResourceManager.GetString("DeleteIndexButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string deleteIndexText {
            get {
                return ResourceManager.GetString("deleteIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder with documents.
        /// </summary>
        internal static string FolderWithDocumentsText {
            get {
                return ResourceManager.GetString("FolderWithDocumentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupDocsLinkTest.
        /// </summary>
        internal static string GroupDocsLinkTest {
            get {
                return ResourceManager.GetString("GroupDocsLinkTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Folder.
        /// </summary>
        internal static string IndexFolderText {
            get {
                return ResourceManager.GetString("IndexFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [In Memory index].
        /// </summary>
        internal static string InMemoryIndexText {
            get {
                return ResourceManager.GetString("InMemoryIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LogTitle {
            get {
                return ResourceManager.GetString("LogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next result.
        /// </summary>
        internal static string NextResultButtonText {
            get {
                return ResourceManager.GetString("NextResultButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Found.
        /// </summary>
        internal static string NothingFoundText {
            get {
                return ResourceManager.GetString("NothingFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous result.
        /// </summary>
        internal static string PreviousResultButtonText {
            get {
                return ResourceManager.GetString("PreviousResultButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search query.
        /// </summary>
        internal static string SearchQueryLabel {
            get {
                return ResourceManager.GetString("SearchQueryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results:.
        /// </summary>
        internal static string SearchResultsTest {
            get {
                return ResourceManager.GetString("SearchResultsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ShowTest {
            get {
                return ResourceManager.GetString("ShowTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Error.
        /// </summary>
        internal static string TechnicalError {
            get {
                return ResourceManager.GetString("TechnicalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface Example.
        /// </summary>
        internal static string UserInterfaceExampleTitle {
            get {
                return ResourceManager.GetString("UserInterfaceExampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewButtonText {
            get {
                return ResourceManager.GetString("ViewButtonText", resourceCulture);
            }
        }
    }
}
